### ISSUE TITLE
Problem with Export to XLS

### ISSUE THREAD

**Issue by SalahAdDin** [jazzband/tablib#168]
Hi, how are you?

Sorry, but, i have the next error:
![problemxls](https://cloud.githubusercontent.com/assets/5034215/4112967/4bf2eb8c-3240-11e4-8ad9-3e4e3a324401.png)

As you see, when i export to xls, i obtain a bad export, with chinese o japanese characters, any times don't get any characters, and other issues, but, when i export to cvs, all is good.

Japanese characters are in a datetime field, see the cvs field:
![problemxls2](https://cloud.githubusercontent.com/assets/5034215/4112983/b93d5ad8-3240-11e4-945b-72ec5ddfae69.png)

Nothing error, all is well.
Can you help me?

**Comment by acdha** [comment]
The problem appears to be three places where strings are incorrectly converted to Unicode by silently ignoring errors:

https://github.com/kennethreitz/tablib/blob/develop/tablib/formats/_xlsx.py#L140
https://github.com/kennethreitz/tablib/blob/develop/tablib/formats/_xlsx.py#L145
https://github.com/kennethreitz/tablib/blob/develop/tablib/formats/_xlsx.py#L148

I noticed this with some Arabic documents but it will apply to any character which is outside of US-ASCII.

In very casual testing, I fixed this by replacing the `unicode()` call with `col.decode('utf-8')`. That should probably be a function which does a type-check for incoming unicode/bytestring/everything else but it's probably worth looking into whether we can normalize bytestrings to unicode on the way in rather than having to special-case it in every encoder.

**Comment by chris-allen** [comment]
I can't seem to find a solution that doesn't require edits to tablib's source as @acdha mentioned.  Any plans to fix this?

**Comment by acdha** [comment]
@chris-allen, @SalahAdDin I don't know if this is still relevant but I stopped working on this due to other challenges, the most pressing one being the use a different XLSX library for performance reasons as our data export sizes increased. I just got permission to release that code over here — all it does is export data but it does work with Unicode text and uses xlsxwriter, which I found to be very CPU/memory-efficient: https://pypi.python.org/pypi/django-tabular-export

**Comment by SalahAdDin** [comment]
Do you recommend use the other package instead this package?

**Comment by acdha** [comment]
@SalahAdDin all I can say is that it worked for my project. tablib does a **LOT** more but I didn't need those extra features as much as I needed performance and Unicode support.

**Comment by KyleXie** [comment]
Is there any plan to fix this? I met an error when export to xls file, it looks well at first, but when you try to open the exported xls file, it says "Excel could not open xxx.xls because some content is unreadable. Do you want to open and repair this workbook?", after repair,  some cells is empty, I lost   some data. I'm not sure if it's related with the issue here.

**Comment by KyleXie** [comment]
JFYI, use the latest revision(master branch) with xlwt v1.2.0, everything works well, seems it fixed my issue.

**Comment by hugovk** [comment]
Closing as fixed. If it's still a problem with the newest release, please leave a comment. Thanks!
