### ISSUE TITLE
Streaming result

### ISSUE THREAD

**Issue by KommuSoft** [jazzband/tablib#601]
Can we make (variants) of the exporters that can "stream" the result. Formats like `.csv`, `.json`, etc. can partially generate a result. This means that it can work with a generator as source, and a generator as result.

This would be useful for web downloads, or tooling that can only use a limited amount of memory to process data, since then the source/result might not fit in memory.

**Comment by claudep** [comment]
Due to the way tablib functions and the API it exposes, I think it would be rather hard to make it stream its output. AFAIK several functionalities expect that the entire content is in memory. Feel free to experiment with the code if you think it's feasible, and reopen the ticket once you have some working code to show. (Note you may have to switch to another lib like numpy if you handle very big files).
